openapi: 3.2.0
info:
  title: Marketplace Geography API
  version: '1'
  description: '# About


    The Marketplace API delivers data that helps users find and evaluate health care insurance plans, providers, and coverage information on the marketplace.'
servers:
- url: https://marketplace.api.healthcare.gov/api/v1
security:
- API Key: []
tags:
- name: Geography
  description: Geographic data, including information on states, counties, and zipcodes.
paths:
  /counties/by/zip/{zipcode}:
    x-summary: List Counties by ZIP
    get:
      tags:
      - Geography
      description: 'Find counties matching ZIP Code (5 digits or prefix thereof).

        This method is suitable for use in typeahead UI completions.'
      parameters:
      - $ref: '#/components/parameters/apikey'
      - $ref: '#/components/parameters/year-with-default'
      - $ref: '#/components/parameters/zipcode'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  counties:
                    items:
                      $ref: '#/components/schemas/ZIPCounty'
                    example:
                    - fips: '12345'
                      name: Sedgwick County
                      state: KS
                      zipcode: '67203'
                    type: array
                type: object
      summary: Get counties by zip by zipcode
      x-summary-source: derived
      operationId: getCountiesByZipByZipcode
      x-operation-id-source: derived
  /counties/{fips}:
    x-summary: County Lookup by FIPS
    get:
      tags:
      - Geography
      description: Get information about a county by its FIPS code.
      parameters:
      - $ref: '#/components/parameters/apikey'
      - $ref: '#/components/parameters/year-with-default'
      - $ref: '#/components/parameters/fips'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/County'
      summary: Get counties by fips
      x-summary-source: derived
      operationId: getCountiesByFips
      x-operation-id-source: derived
  /states:
    x-summary: List States
    get:
      tags:
      - Geography
      description: List all U.S. states.
      parameters:
      - $ref: '#/components/parameters/apikey'
      - $ref: '#/components/parameters/year-with-default'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  states:
                    items:
                      $ref: '#/components/schemas/State'
                    type: array
                    example:
                    - name: Nevada
                      abbrev: NV
                      fips: '32'
                      marketplace_model: SBM
                      shop_marketplace_model: SBM
                      hix_name: Nevada Health Link
                      hix_url: https://www.nevadahealthlink.com/
                      shop_hix_name: Nevada Health Link
                      shop_hix_url: https://www.nevadahealthlink.com/
                      8962_link: ''
                      8965_link: ''
                      assister_program_url: https://www.nevadahealthlink.com/find-assistance/
                    - name: New York
                      abbrev: NY
                      fips: '36'
                      marketplace_model: SBM
                      shop_marketplace_model: SBM
                      hix_name: NY State of Health
                      hix_url: https://nystateofhealth.ny.gov/
                      shop_hix_name: NY State of Health
                      shop_hix_url: https://nystateofhealth.ny.gov/
                      8962_link: ''
                      8965_link: ''
                      assister_program_url: https://nystateofhealth.ny.gov/agent/assistors
                type: object
      summary: Get states
      x-summary-source: derived
      operationId: getStates
      x-operation-id-source: derived
  /states/{abbrev}:
    x-summary: Lookup State
    get:
      tags:
      - Geography
      description: Get a U.S. state from its 2-letter USPS abbreviation.
      parameters:
      - $ref: '#/components/parameters/apikey'
      - description: 2-letter USPS state abbreviation, uppercased.
        in: path
        name: abbrev
        required: true
        x-example: NV
        schema:
          type: string
      - $ref: '#/components/parameters/year-with-default'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'
      summary: Get states by abbrev
      x-summary-source: derived
      operationId: getStatesByAbbrev
      x-operation-id-source: derived
  /states/{abbrev}/medicaid:
    x-summary: State Medicaid Data
    get:
      tags:
      - Geography
      description: Get Medicaid data for a U.S. state for a specific fiscal year.
      parameters:
      - $ref: '#/components/parameters/apikey'
      - description: 2-letter USPS state abbreviation, uppercased.
        in: path
        name: abbrev
        required: true
        x-example: NV
        schema:
          type: string
      - $ref: '#/components/parameters/year-with-default'
      - description: 1-4 A specific fiscal quarter. When not specified it defaults to the most current data for the specified year
        in: query
        name: quarter
        required: false
        x-example: '2'
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StateMedicaid'
      summary: Get states by abbrev medicaid
      x-summary-source: derived
      operationId: getStatesByAbbrevMedicaid
      x-operation-id-source: derived
  /states/{abbrev}/poverty-guidelines:
    x-summary: State Poverty Guidelines
    get:
      tags:
      - Geography
      description: Get U.S. federal poverty guidelines for the provided state.
      parameters:
      - $ref: '#/components/parameters/apikey'
      - description: 2-letter USPS state abbreviation, uppercased.
        in: path
        name: abbrev
        required: true
        x-example: NV
        schema:
          type: string
      - $ref: '#/components/parameters/year-required'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PovertyGuideline'
      summary: Get states by abbrev poverty guidelines
      x-summary-source: derived
      operationId: getStatesByAbbrevPovertyGuidelines
      x-operation-id-source: derived
  /rate-areas:
    x-summary: Rate Area Lookup
    get:
      tags:
      - Geography
      description: Get market year rate area for a given zip/fips/state.
      parameters:
      - $ref: '#/components/parameters/apikey'
      - description: 2-letter USPS state abbreviation
        in: query
        name: state
        required: true
        schema:
          type: string
      - description: 5-digit county FIPS code
        in: query
        name: fips
        required: true
        schema:
          type: number
          format: integer
      - description: 5-digit ZIP Code
        in: query
        name: zipcode
        required: true
        schema:
          type: number
          format: integer
      - description: Insurance market
        in: query
        name: market
        required: false
        schema:
          type: string
          enum:
          - Individual
          - SHOP
          - Any
          default: Individual
      - $ref: '#/components/parameters/year-required'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateArea'
      summary: Get rate areas
      x-summary-source: derived
      operationId: getRateAreas
      x-operation-id-source: derived
components:
  schemas:
    Guideline:
      properties:
        household_size:
          description: Total size of household
          format: integer
          type: number
        guideline:
          description: Federal poverty level guideline
          format: integer
          type: number
      type: object
    LowIncomeChild:
      properties:
        min_age:
          description: Minimum age
          format: integer
          type: number
        max_age:
          description: Maximum age
          format: integer
          type: number
        pc_fpl:
          description: Percentage federal poverty level
          format: float
          type: number
      type: object
    StateMedicaid:
      properties:
        name:
          description: Uppercase name
          type: string
        abbrev:
          description: 2-letter USPS abbreviation
          type: string
        fiscal_year:
          description: 4 digit fiscal year
          format: integer
          type: number
        fiscal_quarter:
          description: Fiscal quarter (1 - 4)
          format: integer
          type: number
        pc_fpl_parent:
          description: Percentage federal poverty level parent caretaker
          format: float
          type: number
        pc_fpl_pregnant:
          description: Percentage medicaid federal poverty level pregnant woman
          format: float
          type: number
        pc_fpl_adult:
          description: Percentage federal poverty level adult group
          format: float
          type: number
        pc_fpl_child_newborn:
          description: Percentage medicaid federal poverty level child
          format: float
          type: number
        pc_fpl_child_1_5:
          description: Percentage medicaid federal poverty level child 1 - 5
          format: float
          type: number
        pc_fpl_child_6_18:
          description: Percentage medicaid federal poverty level child 6 - 18
          format: float
          type: number
        low_income_child:
          description: Low income child eligibility rules
          items:
            $ref: '#/components/schemas/LowIncomeChild'
          type: array
        chip:
          description: Children's Health Insurance Program eligibility rules
          items:
            $ref: '#/components/schemas/LowIncomeChild'
          type: array
      example:
        name: KANSAS
        abbrev: KS
        fiscal_year: 2019
        fiscal_quarter: 1
        pc_fpl_parent: 0.33
        pc_fpl_pregnant: 1.66
        pc_fpl_adult: 0
        pc_fpl_child_newborn: 1.66
        pc_fpl_child_1_5: 1.49
        pc_fpl_child_6_18: 1.33
        low_income_child: []
        chip:
        - min_age: 0
          max_age: 18
          pc_fpl: 2.35
      type: object
    MarketplaceModelEnum:
      enum:
      - FFM
      - FFMPartnership
      - SBM
      - SupportedSBM
      type: string
      properties: {}
    RateArea:
      properties:
        state:
          description: 2-letter USPS abbreviation
          type: string
        area:
          description: Rate area number for the given state.
          type: integer
      type: object
      example:
        state: LA
        area: 7
    County:
      properties:
        fips:
          type: string
          example: '04013'
        name:
          type: string
          example: Maricopa County
        state:
          description: 2-letter USPS state abbreviation
          example: AZ
          type: string
      type: object
    ZIPCounty:
      properties:
        fips:
          format: ^[0-9]{5}$
          type: string
        name:
          type: string
        state:
          format: ^[A-Z]{2}$
          type: string
        zipcode:
          format: ^[0-9]{5}$
          type: string
      type: object
    State:
      properties:
        abbrev:
          description: 2-letter USPS abbreviation
          type: string
        fips:
          description: 2-digit FIPS code
          type: string
        hix_name:
          type: string
        hix_url:
          format: uri
          type: string
        marketplace:
          $ref: '#/components/schemas/MarketplaceModelEnum'
        name:
          type: string
        shop_hix_name:
          type: string
        shop_hix_url:
          format: uri
          type: string
        shop_marketplace:
          $ref: '#/components/schemas/MarketplaceModelEnum'
        8962_link:
          format: uri
          type: string
        8965_link:
          format: uri
          type: string
        assister_program_url:
          format: uri
          type: string
      example:
        name: Nevada
        abbrev: NV
        fips: '32'
        marketplace_model: FFM
        shop_marketplace_model: FFM
        hix_name: Nevada Health Link
        hix_url: https://www.nevadahealthlink.com/
        shop_hix_name: Nevada Health Link
        shop_hix_url: https://www.nevadahealthlink.com/
        8962_link: ''
        8965_link: ''
        assister_program_url: https://www.nevadahealthlink.com/find-assistance/
      type: object
    PovertyGuideline:
      properties:
        add_per_person_after_eight:
          description: For households over eight members add this value for each additional member
          format: integer
          type: number
        guidelines:
          description: Household guidelines
          items:
            $ref: '#/components/schemas/Guideline'
          type: array
      type: object
  parameters:
    zipcode:
      description: 5 digit ZIP Code or 1-4 digit prefix of a ZIP Code
      in: path
      name: zipcode
      required: true
      x-example: '19123'
      schema:
        type: string
    year-with-default:
      x-example: 2019
      name: year
      description: 4 digit market year (Defaults to the current year when not specified).
      in: query
      required: false
      schema:
        type: number
        format: integer
    apikey:
      name: apikey
      description: API key used for authentication
      in: query
      required: true
      x-example: d687412e7b53146b2631dc01974ad0a4
      schema:
        type: string
    fips:
      description: 5-digit county FIPS code
      in: path
      name: fips
      required: true
      x-example: '37057'
      schema:
        type: string
    year-required:
      x-example: 2019
      name: year
      description: 4 digit market year.
      in: query
      required: true
      schema:
        type: number
        format: integer
  securitySchemes:
    API_Key:
      x-summary: API Key Auth
      description: Your API key should be included as a query parameter with the request. You can [fill out this form](https://cms.gov1.qualtrics.com/jfe/form/SV_4N2GHCJfNuX7n8x) to request an API key.
      type: apiKey
      in: query
      name: apikey
      x-example: d687412e7b53146b2631dc01974ad0a4
